server:
  port: 8070
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/blog?serverTimezone=Asia/Seoul&validationQuery="select 1"
    #url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&validationQuery="select 1"
    username: hak
    password: hak1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        #show-sql: true
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false